name: CI Pico Bridge

on:
  push:
    
jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4

      - name: 'Install dependencies'
        run: |
          sudo apt-get install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi

      - name: 'Update Submodules'
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: 'Configure'
        run: |
          cd Software/pico-uart-bridge
          mkdir -p build
          cmake -B build

      - name: 'Build'
        run: |
          make -C Software/pico-uart-bridge/build

      - name: 'Upload binary'
        uses: actions/upload-artifact@v4
        with:
          name: pico-uart-bridge.uf2
          path: Software/pico-uart-bridge/build/uart_bridge.uf2
          retention-days: 5
