name: Build flash.bin

on:
  push:
    branches:
      - main  # Run when code is pushed to main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, nvme] # Specify the environment to run the build
    
    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true  # Initialize submodules

    # Initialize submodules if needed
    - name: Initialize submodules
      run: git submodule update --init --recursive

    # Install build dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-arm-linux-gnueabi u-boot-tools \
                               python3-pip python3-setuptools python3-wheel

    # Install pip dependencies, not needed any more
    # - name: Install pip dependencies
    #   run: |
    #     python3 -m pip install --upgrade pip
    #     python3 -m pip install pylibfdt

    # Configure the build
    - name: Configure buildroot
      working-directory: Software/buildroot
      run: |
        BR2_EXTERNAL=../simple_sbc make f1c200s_simple_sbc_defconfig

    # Build the flash.bin
    - name: Build flash.bin
      working-directory: Software/buildroot
      run: |
        make clean
        make -j$(nproc)

    # Archive the built flash.bin file
    - name: Upload flash.bin
      uses: actions/upload-artifact@v4
      with:
        name: flash.bin
        path: Software/buildroot/output/images/flash.bin  # Replace with actual path to flash.bin
